name: Secrets Demo

on:
  workflow_dispatch:

jobs:
  read-secrets:
    runs-on: ubuntu-latest
    env:
      DOCKER_PASS: thisisdockerpassinenv
      
    steps:
      - name: Read & Print Secret Value
        run: |
          echo "${{ secrets.MY_SECRET_MESSAGE }}"
          echo "Environment: $DOCKER_PASS"
          echo "DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}"
          echo "DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}"
