name: Secrets Demo

on:
  push:

jobs:
  read-secrets:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check if secret is set (safely)
        run: |
          if [ -n "${{ secrets.MY_SECRET_MESSAGE }}" ]; then
            echo "The secret is set: True"
          else
            echo "The secret is set: False"
          fi

      - name: Try printing the secret directly
        run: echo "${{ secrets.MY_SECRET_MESSAGE }}"

      - name: Use secret as environment variable
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "Docker username is: $DOCKER_USERNAME"
          echo "Docker Token: $DOCKER_TOKEN"
