name: Secrets Demo

on:
  workflow_dispatch:

jobs:
  read-secrets:
    runs-on: ubuntu-latest
    env:
      DOCKER_PASS: hello
      
    steps:
      - name: Read & Print Secret Value
        run: |
          echo "${{ secrets.MY_SECRET_MESSAGE }}"
          echo "Environment: $DOCKER_PASS"
